### ISSUE TITLE
crear el archivo .editorconfig

### ISSUE THREAD

**Issue by Yelro** [espam-cv/tc-imc#3]

**Comment by Yelro** [comment]
# Crear el archivo .editorconfig
Para mantener estilos de codificación consistentes

## Configuración
* espacios del Tab
* al final de una línea aplicar \n
* indica codificación de caracteres
* elimina el espacio al final de una línea
* deja al final del archivo una línea en blanco
* número de caracteres por línea

**Comment by luischigar** [comment]
Tarea terminada con el pr #4
